export const TRANSFER_MUTATION_FIXTURES = [
  ["helper parameter transfer", "const db = new PrismaClient(); function destroy(client: unknown) {} destroy(db);"],
  ["helper return transfer", "const db = new PrismaClient(); function pass() { return db; } pass();"],
  ["object holder", "const db = new PrismaClient(); const holder = { db };"],
  ["array holder", "const db = new PrismaClient(); const holder = [db];"],
  ["conditional transfer", "const db = new PrismaClient(); const alias = condition ? db : db;"],
  ["constructor helper pass", "consume(new PrismaClient());"],
  ["constructor object store", "const holder = { client: new PrismaClient() };"],
  ["constructor conditional", "const client = condition ? new PrismaClient() : new PrismaClient();"],
  ["factory helper pass", "const make = () => new PrismaClient(); consume(make());"],
  ["factory array store", "const make = () => new PrismaClient(); const holder = [make()];"],
  ["factory conditional", "const make = () => new PrismaClient(); const client = condition ? make() : make();"],
  ["ambient adapter handoff", "declare function createPrismaBasicActivationCountPort(client: PrismaClient): void; const db = new PrismaClient(); createPrismaBasicActivationCountPort(db);"],
  ["untyped adapter implementation overload", "function createPrismaBasicActivationCountPort(client: PrismaClient): void; function createPrismaBasicActivationCountPort(client: unknown) {} const db = new PrismaClient(); createPrismaBasicActivationCountPort(db);"],
  ["typed adapter implementation overload", "function createPrismaBasicActivationCountPort(client: PrismaClient): void; function createPrismaBasicActivationCountPort(client: PrismaClient) {} const db = new PrismaClient(); createPrismaBasicActivationCountPort(db);"],
  ["same-name shadow adapter", "export function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } { function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } const db = new PrismaClient(); createPrismaBasicActivationCountPort(db); }"],
  ["direct constructor adapter handoff", "export function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } createPrismaBasicActivationCountPort(new PrismaClient());"],
  ["direct explicit factory adapter handoff", "export function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } function make(): PrismaClient { return new PrismaClient(); } createPrismaBasicActivationCountPort(make());"],
  ["direct inferred factory adapter handoff", "export function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } const make = () => new PrismaClient(); createPrismaBasicActivationCountPort(make());"],
  ["constructor alias", "const ClientCtor = PrismaClient;"],
  ["constructor bind", "const BoundClient = PrismaClient.bind(null);"],
  ["constructor call", "PrismaClient.call(null);"],
  ["constructor apply", "PrismaClient.apply(null, []);"],
  ["constructor helper argument", "consume(PrismaClient);"],
  ["constructor return", "function expose() { return PrismaClient; }"],
  ["constructor object holder", "const holder = { PrismaClient };"],
  ["constructor array holder", "const holder = [PrismaClient];"],
  ["constructor spread", "const holder = { ...PrismaClient };"],
  ["adapter reassignment", "export function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } createPrismaBasicActivationCountPort = evil; const db = new PrismaClient(); createPrismaBasicActivationCountPort(db);"],
  ["adapter compound reassignment", "export function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } createPrismaBasicActivationCountPort ||= evil;"],
  ["adapter alias", "export function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } const alias = createPrismaBasicActivationCountPort;"],
  ["adapter object holder", "export function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } const holder = { createPrismaBasicActivationCountPort };"],
  ["adapter array holder", "export function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } const holder = [createPrismaBasicActivationCountPort];"],
  ["adapter property storage", "export function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } holder.adapter = createPrismaBasicActivationCountPort;"],
  ["adapter helper argument", "export function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } consume(createPrismaBasicActivationCountPort);"],
  ["adapter return", "export function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } function expose() { return createPrismaBasicActivationCountPort; }"],
  ["adapter call indirection", "export function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } createPrismaBasicActivationCountPort.call(null, client);"],
  ["adapter apply indirection", "export function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } createPrismaBasicActivationCountPort.apply(null, [client]);"],
  ["adapter bind indirection", "export function createPrismaBasicActivationCountPort(client: PrismaClient) { client.policy.count(); } const bound = createPrismaBasicActivationCountPort.bind(null);"],
] as const satisfies readonly (readonly [string, string])[];
