export const CLIENT_MUTATION_FIXTURES = [
  ["client alias find", "const db = new PrismaClient(); const alias = db; alias.policy.findMany();"],
  ["delegate alias write", "const db = new PrismaClient(); const delegate = db.policy; delegate.deleteMany();"],
  ["destructured delegate aggregate", "const db = new PrismaClient(); const { risk } = db; risk.aggregate();"],
  ["static bracket groupBy", "const db = new PrismaClient(); db[\"project\"][\"groupBy\"]();"],
  ["dynamic delegate read", "const db = new PrismaClient(); const model = \"policy\"; db[model].count();"],
  ["dynamic method read", "const db = new PrismaClient(); const method = \"count\"; db.policy[method]();"],
  ["bracket method write", "const db = new PrismaClient(); db[\"policy\"][\"count\"] = replacement;"],
  ["assigned raw call", "const db = new PrismaClient(); let alias; alias = db; alias[\"$queryRaw\"]();"],
  ["direct raw execute", "const db = new PrismaClient(); db.$executeRawUnsafe();"],
  ["delegate bracket read", "const db = new PrismaClient(); db.policy[\"findFirst\"]();"],
  ["unknown delegate count", "const db = new PrismaClient(); db.unknown.count();"],
  ["parenthesized call", "const db = new PrismaClient(); (db.policy).deleteMany();"],
  ["asserted call", "const db = new PrismaClient(); (db.policy as unknown as { findMany(): void }).findMany();"],
  ["type-asserted call", "const db = new PrismaClient(); (<unknown>db.policy as { aggregate(): void }).aggregate();"],
  ["satisfies call", "const db = new PrismaClient(); (db.policy satisfies unknown).groupBy();"],
  ["non-null call", "const db = new PrismaClient(); db.policy!.findFirst();"],
  ["destructured method", "const db = new PrismaClient(); const { deleteMany } = db.policy; deleteMany();"],
  ["destructured count method", "const db = new PrismaClient(); const { count } = db.policy; count();"],
  ["aliased count method", "const db = new PrismaClient(); const count = db.policy.count; count();"],
  ["destructured disconnect", "const db = new PrismaClient(); const { $disconnect } = db; $disconnect();"],
  ["destructured member owner", "const db = new PrismaClient(); const { bind } = db.policy.findMany; bind();"],
  ["tagged query raw", "const db = new PrismaClient(); db.$queryRaw`SELECT 1`;"],
  ["tagged execute raw", "const db = new PrismaClient(); db[\"$executeRaw\"]`DELETE FROM x`;"],
  ["forbidden method read", "const db = new PrismaClient(); const read = db.policy.findMany;"],
  ["inferred factory forbidden call", "const createClient = () => new PrismaClient(); const db = createClient(); db.policy.findMany();"],
  ["optional delegate call", "const db = new PrismaClient(); db?.policy.count();"],
  ["optional method call", "const db = new PrismaClient(); db.policy?.count();"],
  ["array destructuring transfer", "const db = new PrismaClient(); const [alias] = [db];"],
  ["direct constructor delegate", "new PrismaClient().policy.deleteMany();"],
  ["direct constructor raw", "new PrismaClient().$queryRawUnsafe();"],
  ["direct explicit factory call", "function make(): PrismaClient { return new PrismaClient(); } make().policy.findMany();"],
  ["direct inferred factory call", "const make = () => new PrismaClient(); make().risk.aggregate();"],
] as const satisfies readonly (readonly [string, string])[];
